// Mocks generated by Mockito 5.1.0 from annotations
// in mvc/test/user_detail/view_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:misc/misc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mvc/user_detail/model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Model].
///
/// See the documentation for Mockito's code generation for more information.
class MockModel extends _i1.Mock implements _i2.Model {
  MockModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> fetchUserDetail(String? login) =>
      (super.noSuchMethod(Invocation.method(#fetchUserDetail, [login]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  void getUserDetail(_i4.SignalApiView? state, _i4.UserOverview? data) =>
      super.noSuchMethod(Invocation.method(#getUserDetail, [state, data]),
          returnValueForMissingStub: null);
  @override
  void destroy() => super.noSuchMethod(Invocation.method(#destroy, []),
      returnValueForMissingStub: null);
}
