// Mocks generated by Mockito 5.1.0 from annotations
// in bloc_pattern/test/user_detail/view_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:bloc/bloc.dart' as _i5;
import 'package:bloc_pattern/user_detail/user_detail_cubit.dart' as _i2;
import 'package:misc/model/user_overview.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserDetailState_0 extends _i1.Fake implements _i2.UserDetailState {}

/// A class which mocks [UserDetailCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDetailCubit extends _i1.Mock implements _i2.UserDetailCubit {
  MockUserDetailCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserDetailState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeUserDetailState_0()) as _i2.UserDetailState);
  @override
  _i3.Stream<_i2.UserDetailState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i2.UserDetailState>.empty())
          as _i3.Stream<_i2.UserDetailState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void getUserDetail(_i4.UserOverview? user) =>
      super.noSuchMethod(Invocation.method(#getUserDetail, [user]),
          returnValueForMissingStub: null);
  @override
  void emit(_i2.UserDetailState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onChange(_i5.Change<_i2.UserDetailState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
