// Mocks generated by Mockito 5.1.0 from annotations
// in bloc_pattern/test/mine/view_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:bloc/bloc.dart' as _i4;
import 'package:bloc_pattern/mine/mine_cubit.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMineState_0 extends _i1.Fake implements _i2.MineState {}

/// A class which mocks [MineCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMineCubit extends _i1.Mock implements _i2.MineCubit {
  MockMineCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MineState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeMineState_0()) as _i2.MineState);
  @override
  _i3.Stream<_i2.MineState> get stream => (super.noSuchMethod(
      Invocation.getter(#stream),
      returnValue: Stream<_i2.MineState>.empty()) as _i3.Stream<_i2.MineState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void getMineDetail() =>
      super.noSuchMethod(Invocation.method(#getMineDetail, []),
          returnValueForMissingStub: null);
  @override
  void emit(_i2.MineState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onChange(_i4.Change<_i2.MineState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
