// Mocks generated by Mockito 5.1.0 from annotations
// in mvp/test/user_detail/view_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:misc/model/user_overview.dart' as _i5;
import 'package:misc/ui/signal_api_view.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mvp/user_detail/presenter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Presenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPresenter extends _i1.Mock implements _i2.Presenter {
  MockPresenter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setView(_i3.SignalApiView? view) =>
      super.noSuchMethod(Invocation.method(#setView, [view]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<void> getUserDetail(_i5.UserOverview? user) =>
      (super.noSuchMethod(Invocation.method(#getUserDetail, [user]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}
