// Mocks generated by Mockito 5.1.0 from annotations
// in mvvm/test/user_detail/view_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:misc/model/user_detail.dart' as _i4;
import 'package:misc/model/user_overview.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mvvm/user_detail/view_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockViewModel extends _i1.Mock implements _i2.ViewModel {
  MockViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.UserDetail> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i4.UserDetail>.empty())
          as _i3.Stream<_i4.UserDetail>);
  @override
  _i3.Future<void> getUserDetail(_i5.UserOverview? user) =>
      (super.noSuchMethod(Invocation.method(#getUserDetail, [user]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  void destroy() => super.noSuchMethod(Invocation.method(#destroy, []),
      returnValueForMissingStub: null);
}
